export const QUERY__LOAD = "QUERY__LOAD";
export const QUERY__LOAD_SUCCESS = "QUERY__LOAD_SUCCESS";
export const QUERY__LOAD_FAILURE = "QUERY__LOAD_FAILURE";
export const QUERY__RELEASE = "QUERY__RELEASE";

export const INDEX_ROUTE__SET_NEW_PLAYLIST_TITLE =
  "INDEX_ROUTE__SET_NEW_PLAYLIST_TITLE";
export const INDEX_ROUTE__CREATE_PLAYLIST = "INDEX_ROUTE__CREATE_PLAYLIST";
