export const ROUTER__ENTERED = "ROUTER__ENTERED";
export const ROUTER__LEFT = "ROUTER__LEFT";

export const QUERY__LOAD = "QUERY__LOAD";
export const QUERY__LOAD_SUCCESS = "QUERY__LOAD_SUCCESS";
export const QUERY__LOAD_FAILURE = "QUERY__LOAD_FAILURE";
export const QUERY__RELEASE = "QUERY__RELEASE";

export const INDEX_ROUTE__SET_NEW_PLAYLIST_TITLE =
  "INDEX_ROUTE__SET_NEW_PLAYLIST_TITLE";
export const INDEX_ROUTE__CREATE_PLAYLIST = "INDEX_ROUTE__CREATE_PLAYLIST";

export const PLAYLIST_ROUTE__SET_RATING = "PLAYLIST_ROUTE__SET_RATING";
export const PLAYLIST_ROUTE__SET_NEW_SONG_PERFORMER =
  "PLAYLIST_ROUTE__SET_NEW_SONG_PERFORMER";
export const PLAYLIST_ROUTE__SET_NEW_SONG_TITLE =
  "PLAYLIST_ROUTE__SET_NEW_SONG_TITLE";
export const PLAYLIST_ROUTE__RESET_NEW_SONG_INPUTS =
  "PLAYLIST_ROUTE__RESET_NEW_SONG_INPUTS";
export const PLAYLIST_ROUTE__TOGGLE_SELECTED_ID =
  "PLAYLIST_ROUTE__TOGGLE_SELECTED_ID";
export const PLAYLIST_ROUTE__RESET_SELECTED_IDS =
  "PLAYLIST_ROUTE__RESET_SELECTED_IDS";
export const PLAYLIST_ROUTE__DELETE_SELECTED =
  "PLAYLIST_ROUTE__DELETE_SELECTED";
export const PLAYLIST_ROUTE__ADD_SONG = "PLAYLIST_ROUTE__ADD_SONG";
export const PLAYLIST_ROUTE__SET_POSITION = "PLAYLIST_ROUTE__SET_POSITION";
export const PLAYLIST_ROUTE__MERGE_REPOSITION_PATCH =
  "PLAYLIST_ROUTE__MERGE_REPOSITION_PATCH";
export const PLAYLIST_ROUTE__REMOVE_FROM_REPOSITION_PATCH =
  "PLAYLIST_ROUTE__REMOVE_FROM_REPOSITION_PATCH";
export const PLAYLIST_ROUTE__SET_DRAGGING_SONG_ID =
  "PLAYLIST_ROUTE__SET_DRAGGING_SONG_ID";
export const PLAYLIST_ROUTE__SET_DRAGGING_INDICATOR_SONG_ID =
  "PLAYLIST_ROUTE__SET_DRAGGING_INDICATOR_SONG_ID";
